### ISSUE TITLE
【bugfix】组件重复注册

### ISSUE THREAD

**Issue by jiyeme** [GeekQiaQia/vue3.0-template-admin#29]
控制台输出：

```
onMounted personalCenter.vue personalCenter.vue:158 
onActivated personalCenter.vue personalCenter.vue:154
onMounted personalCenter.vue personalCenter.vue:158
onActivated personalCenter.vue personalCenter.vue:154
onMounted personalCenter.vue personalCenter.vue:158
onActivated personalCenter.vue
```

dom截图:
![QQ截图20210825080002.png](https://i.loli.net/2021/08/25/RY92wLKX17hCaJG.png)

**Comment by jiyeme** [comment]
载入次数与导航标签数相等，
经查找，在AppMain中，`router-view`在`el-tab-pane`中；
导致标签有n个，`router-view`执行n次；
将`router-view`从`el-tab-pane`中移出似乎就能解决 (经测试暂时能用)

变更前
```
     <el-tab-pane
        v-for="item in tabsOption"
        :key="item.route"
        :closable="item.route !== '/home'"
        :label="item.title[lang]"
        :name="item.route"
      >
        <router-view v-if="$route.meta.keepAlive" v-slot="{ Component }">
          <transition name="fade" mode="out-in">
            <component :is="Component" :key="$route.path" />
          </transition>
        </router-view>

        <router-view v-else v-slot="{ Component }">
          <transition name="fade" mode="out-in">
            <keep-alive>
              <component :is="Component" :key="$route.path" />
            </keep-alive>
          </transition>
        </router-view>
      </el-tab-pane>
```

变更后：
```
     <el-tab-pane
        v-for="item in tabsOption"
        :key="item.route"
        :closable="item.route !== '/home'"
        :label="item.title[lang]"
        :name="item.route"
      ></el-tab-pane>
      <router-view v-if="$route.meta.keepAlive" v-slot="{ Component }">
        <transition name="fade" mode="out-in">
          <component :is="Component" :key="$route.path" />
        </transition>
      </router-view>

      <router-view v-else v-slot="{ Component }">
        <transition name="fade" mode="out-in">
          <keep-alive>
            <component :is="Component" :key="$route.path" />
          </keep-alive>
        </transition>
      </router-view>
```

**Comment by GeekQiaQia** [comment]
ok  ,我也发现了这个问题，vue2的思路是没问题的，这个得学习一下vue3.0的router-view，还是 Elment Plus 的el-tab内部做了什么事情。 欢迎pr 哈

**Comment by GeekQiaQia** [comment]
> 载入次数与导航标签数相等，
> 经查找，在AppMain中，`router-view`在`el-tab-pane`中；
> 导致标签有n个，`router-view`执行n次；
> 将`router-view`从`el-tab-pane`中移出似乎就能解决 (经测试暂时能用)
> 
> 变更前
> 
> ```
>      <el-tab-pane
>         v-for="item in tabsOption"
>         :key="item.route"
>         :closable="item.route !== '/home'"
>         :label="item.title[lang]"
>         :name="item.route"
>       >
>         <router-view v-if="$route.meta.keepAlive" v-slot="{ Component }">
>           <transition name="fade" mode="out-in">
>             <component :is="Component" :key="$route.path" />
>           </transition>
>         </router-view>
> 
>         <router-view v-else v-slot="{ Component }">
>           <transition name="fade" mode="out-in">
>             <keep-alive>
>               <component :is="Component" :key="$route.path" />
>             </keep-alive>
>           </transition>
>         </router-view>
>       </el-tab-pane>
> ```
> 
> 变更后：
> 
> ```
>      <el-tab-pane
>         v-for="item in tabsOption"
>         :key="item.route"
>         :closable="item.route !== '/home'"
>         :label="item.title[lang]"
>         :name="item.route"
>       ></el-tab-pane>
>       <router-view v-if="$route.meta.keepAlive" v-slot="{ Component }">
>         <transition name="fade" mode="out-in">
>           <component :is="Component" :key="$route.path" />
>         </transition>
>       </router-view>
> 
>       <router-view v-else v-slot="{ Component }">
>         <transition name="fade" mode="out-in">
>           <keep-alive>
>             <component :is="Component" :key="$route.path" />
>           </keep-alive>
>         </transition>
>       </router-view>
> ```

ok  ,我也发现了这个问题，vue2的思路是没问题的，这个得学习一下vue3.0的router-view，还是 Elment Plus 的el-tab内部做了什么事情。 欢迎pr 哈

**Comment by GeekQiaQia** [comment]
感谢您的issue。el-tab的作用，只做tab的展示，剩下的让router-view渲染路由组件，所以不应该包裹在el-tab中。
