### ISSUE TITLE
【fixbug】el-tooltip:provide a valid default slot 

### ISSUE THREAD

**Issue by jiyeme** [GeekQiaQia/vue3.0-template-admin#35]
当任何一个角色状态为0（锁定）时，页面排版错乱，控制台报错。
```
Uncaught (in promise) ElementPlusError: [[ElTooltip]] you need to provide a valid default slot.
```
将判断条件改为非零时，`锁定`状态显示正常。
所以，使用非零标记可以解决这个问题。

但是，我没有找出这个0状态问题在哪里。

**Comment by GeekQiaQia** [comment]
ok 稍后我看看

**Comment by GeekQiaQia** [comment]
> 当任何一个角色状态为0（锁定）时，页面排版错乱，控制台报错。
> 
> ```
> Uncaught (in promise) ElementPlusError: [[ElTooltip]] you need to provide a valid default slot.
> ```
> 
> 将判断条件改为非零时，`锁定`状态显示正常。
> 所以，使用非零标记可以解决这个问题。
> 
> 但是，我没有找出这个0状态问题在哪里。
```
      <el-tooltip v-if="scope.row.state != 0" class="item" effect="dark" content="删除" placement="bottom">
              <el-button circle plain type="danger" icon="el-icon-minus" size="small" @click="onDelete(scope.$index, scope.row)">
               </el-button>
     </el-tooltip>
```
这里有个小bug,将v-if放在tooltip外边即可，他现在新版本的element tooltip内部做了不为空的校验
