### ISSUE TITLE
全屏不兼容报错

### ISSUE THREAD

**Issue by MikelPan** [GeekQiaQia/vue3.0-template-admin#54]
Property 'msExitFullscreen' does not exist on type 'Document'. Did you mean 'exitFullscreen'?

编译时报错，属性不存在

**Comment by GeekQiaQia** [comment]
> Property 'msExitFullscreen' does not exist on type 'Document'. Did you mean 'exitFullscreen'?
> 
> 编译时报错，属性不存在

你好，可以提供一下复现环境吗

**Comment by Gavin-yh** [comment]
你好，编译时，是怎么操作的，导致的问题

**Comment by MikelPan** [comment]
使用yarn run dev，执行package里面的命令，这个不是直接把仓库拉下来使用的，是初始化为vue项目，然后对应的main.ts 参照修改，在编译的时候遇到的问题


| |
Mr.Pan
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年11月2日 ***@***.***> 写道：

你好，编译时，是怎么操作的，导致的问题

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by GeekQiaQia** [comment]
场景未复现，issue 暂时关闭，如有需要支持，可进入技术交流群进行讨论
