### ISSUE TITLE
【bug】预览失败，无法「登录」+「获取验证码」

### ISSUE THREAD

**Issue by wynn-w** [GeekQiaQia/vue3.0-template-admin#56]
情景：示例账户「surper@outlook.com + 123456」登录失败，转用户注册，点击「获取验证码」产生异常。
异常返回信息：
![image](https://user-images.githubusercontent.com/75034279/143533906-ac44d485-bb2c-4d47-a0ce-fc2990e48b4b.png)

**Comment by GeekQiaQia** [comment]
> 情景：示例账户「[surper@outlook.com](mailto:surper@outlook.com) + 123456」登录失败，转用户注册，点击「获取验证码」产生异常。 异常返回信息： ![image](https://user-images.githubusercontent.com/75034279/143533906-ac44d485-bb2c-4d47-a0ce-fc2990e48b4b.png)
你好，登录[预览地址](https://geekqiaqia.github.io/vue3.0-template-admin/#/home)可以正常登录的，注册和获取验证码，在演示中没有进行mock数据，只是作为一个接口的扩展和示例，屏蔽掉mock，接入您的真实后端api即可；
