### ISSUE TITLE
<keep-alive>缓存的路由没有被真正清除掉

### ISSUE THREAD

**Issue by SsikRoEsor** [GeekQiaQia/vue3.0-template-admin#68]
<keep-alive>缓存的路由，在修改页面数据后，在顶部tabs中关闭缓存路由后，重新从左侧打开修改数据了的路由组件，数据依然存在。

**Comment by GeekQiaQia** [comment]
> 
是的没错 ，在layout main 中，内部是走了keep-alive 的分支；

**Comment by GeekQiaQia** [comment]
> 缓存的路由，在修改页面数据后，在顶部tabs中关闭缓存路由后，重新从左侧打开修改数据了的路由组件，数据依然存在。

你可以选择，在路由配置中配置是否走keep-alive 实例缓存
