### ISSUE TITLE
请问作者，预览页面的用户名密码是什么？

### ISSUE THREAD

**Issue by neilbowman666** [GeekQiaQia/vue3.0-template-admin#70]
https://geekqiaqia.github.io/vue3.0-template-admin

请问作者，预览页面的用户名密码是什么？

在文档中没看到默认的用户名密码，注册用户会报 405。

**Comment by GeekQiaQia** [comment]
> https://geekqiaqia.github.io/vue3.0-template-admin
> 
> 请问作者，预览页面的用户名密码是什么？
> 
> 在文档中没看到默认的用户名密码，注册用户会报 405。
正常就是placeholder 中的提示，是内部做的mock数据；您可以换个chrome浏览器或者切换一下网络代理试试，

**Comment by GeekQiaQia** [comment]
> https://geekqiaqia.github.io/vue3.0-template-admin
如果还是有问题，可以进群交流一下，发一下您的复现场景，排查一下问题；
