### ISSUE TITLE
多点几个不同的模块，然后退出登录 vue-router 会报错

### ISSUE THREAD

**Issue by Doyouhavefreestyle** [GeekQiaQia/vue3.0-template-admin#83]
![image](https://user-images.githubusercontent.com/40022209/180719659-5eccc12a-8728-486c-92b1-e8c0f9efddec.png)

**Comment by GeekQiaQia** [comment]
> ![image](https://user-images.githubusercontent.com/40022209/180719659-5eccc12a-8728-486c-92b1-e8c0f9efddec.png)
OK 我们尝试复现一下场景

**Comment by EAGLEliuS** [comment]
在src>layout>AppMain裡面的 <keep-alive>標籤 加入 :include="$route.name"

**Comment by GeekQiaQia** [comment]
> 在src>layout>AppMain裡面的 keep-alive標籤 加入 :include="$route.name"

感谢，已修复
